#############################################################################
# Makefile for building: hovel
# Generated by qmake (2.01a) (Qt 4.7.0) on: Fri Jan 8 20:38:51 2010
# Project:  hovel.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.0/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile hovel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.0/include/QtCore -I/usr/local/Trolltech/Qt-4.7.0/include/QtGui -I/usr/local/Trolltech/Qt-4.7.0/include/QtXml -I/usr/local/Trolltech/Qt-4.7.0/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.0/lib -lQtXml -L/usr/local/Trolltech/Qt-4.7.0/lib -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		hovelmodel.cpp \
		projecttreeview.cpp \
		folderitem.cpp \
		textitem.cpp \
		projectitem.cpp \
		bookitem.cpp \
		hovelitem.cpp \
		propertiesview.cpp \
		propertiesproxymodel.cpp \
		chapteritem.cpp \
		textedit.cpp \
		export.cpp moc_mainwindow.cpp \
		moc_projecttreeview.cpp \
		moc_textedit.cpp \
		qrc_hovel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		hovelmodel.o \
		projecttreeview.o \
		folderitem.o \
		textitem.o \
		projectitem.o \
		bookitem.o \
		hovelitem.o \
		propertiesview.o \
		propertiesproxymodel.o \
		chapteritem.o \
		textedit.o \
		export.o \
		moc_mainwindow.o \
		moc_projecttreeview.o \
		moc_textedit.o \
		qrc_hovel.o
DIST          = /usr/local/Trolltech/Qt-4.7.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/include_source_dir.prf \
		hovel.pro
QMAKE_TARGET  = hovel
DESTDIR       = 
TARGET        = hovel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hovel.pro  /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.0/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.7.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.7.0/lib/libQtGui.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile hovel.pro
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.0/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.7.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.7.0/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile hovel.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hovel1.0.0 || $(MKDIR) .tmp/hovel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hovel1.0.0/ && $(COPY_FILE) --parents mainwindow.h hovelitem.h hovelmodel.h projecttreeview.h serialise.h folderitem.h textitem.h projectitem.h bookitem.h propertiesview.h propertiesproxymodel.h chapteritem.h textedit.h export.h .tmp/hovel1.0.0/ && $(COPY_FILE) --parents hovel.qrc .tmp/hovel1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp hovelmodel.cpp projecttreeview.cpp folderitem.cpp textitem.cpp projectitem.cpp bookitem.cpp hovelitem.cpp propertiesview.cpp propertiesproxymodel.cpp chapteritem.cpp textedit.cpp export.cpp .tmp/hovel1.0.0/ && (cd `dirname .tmp/hovel1.0.0` && $(TAR) hovel1.0.0.tar hovel1.0.0 && $(COMPRESS) hovel1.0.0.tar) && $(MOVE) `dirname .tmp/hovel1.0.0`/hovel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hovel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_projecttreeview.cpp moc_textedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_projecttreeview.cpp moc_textedit.cpp
moc_mainwindow.cpp: hovelmodel.h \
		projectitem.h \
		hovelitem.h \
		serialise.h \
		projecttreeview.h \
		propertiesview.h \
		propertiesproxymodel.h \
		mainwindow.h
	/usr/local/Trolltech/Qt-4.7.0/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_projecttreeview.cpp: projecttreeview.h
	/usr/local/Trolltech/Qt-4.7.0/bin/moc $(DEFINES) $(INCPATH) projecttreeview.h -o moc_projecttreeview.cpp

moc_textedit.cpp: textedit.h
	/usr/local/Trolltech/Qt-4.7.0/bin/moc $(DEFINES) $(INCPATH) textedit.h -o moc_textedit.cpp

compiler_rcc_make_all: qrc_hovel.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_hovel.cpp
qrc_hovel.cpp: hovel.qrc \
		images/chapter.png \
		images/book.png \
		images/add.png \
		images/folder.png \
		images/tree.png \
		images/text.png
	/usr/local/Trolltech/Qt-4.7.0/bin/rcc -name hovel hovel.qrc -o qrc_hovel.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		hovelmodel.h \
		projectitem.h \
		hovelitem.h \
		serialise.h \
		projecttreeview.h \
		propertiesview.h \
		propertiesproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		hovelmodel.h \
		projectitem.h \
		hovelitem.h \
		serialise.h \
		projecttreeview.h \
		propertiesview.h \
		propertiesproxymodel.h \
		bookitem.h \
		chapteritem.h \
		textitem.h \
		textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

hovelmodel.o: hovelmodel.cpp hovelmodel.h \
		projectitem.h \
		hovelitem.h \
		serialise.h \
		bookitem.h \
		textitem.h \
		folderitem.h \
		chapteritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hovelmodel.o hovelmodel.cpp

projecttreeview.o: projecttreeview.cpp projecttreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projecttreeview.o projecttreeview.cpp

folderitem.o: folderitem.cpp folderitem.h \
		hovelitem.h \
		serialise.h \
		textitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderitem.o folderitem.cpp

textitem.o: textitem.cpp textitem.h \
		hovelitem.h \
		serialise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textitem.o textitem.cpp

projectitem.o: projectitem.cpp projectitem.h \
		hovelitem.h \
		serialise.h \
		bookitem.h \
		folderitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectitem.o projectitem.cpp

bookitem.o: bookitem.cpp bookitem.h \
		hovelitem.h \
		serialise.h \
		folderitem.h \
		textitem.h \
		chapteritem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookitem.o bookitem.cpp

hovelitem.o: hovelitem.cpp hovelitem.h \
		serialise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hovelitem.o hovelitem.cpp

propertiesview.o: propertiesview.cpp propertiesview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propertiesview.o propertiesview.cpp

propertiesproxymodel.o: propertiesproxymodel.cpp propertiesproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propertiesproxymodel.o propertiesproxymodel.cpp

chapteritem.o: chapteritem.cpp chapteritem.h \
		hovelitem.h \
		serialise.h \
		textitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chapteritem.o chapteritem.cpp

textedit.o: textedit.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

export.o: export.cpp export.h \
		hovelmodel.h \
		projectitem.h \
		hovelitem.h \
		serialise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o export.o export.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_projecttreeview.o: moc_projecttreeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projecttreeview.o moc_projecttreeview.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

qrc_hovel.o: qrc_hovel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_hovel.o qrc_hovel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

